packages:
  - '.'

overrides:
  debug@<2.6.9: '>=2.6.9'
  underscore@>=1.3.2 <1.12.1: '>=1.12.1'
  log4js@<6.4.0: '>=6.4.0'
  '@cypress/request@<=2.88.12': '>=3.0.0'
  tough-cookie@<4.1.3: '>=4.1.3'
  uplot@<1.6.31: '>=1.6.31'
  nanoid@<3.3.8: '>=3.3.8'
  serialize-javascript@>=6.0.0 <6.0.2: '>=6.0.2'
  prismjs@<1.30.0: '>=1.30.0'
  dompurify@<3.2.4: '>=3.2.4'
  form-data@<2.5.4: '>=2.5.4'
